[project]
name = "1-impdh1"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sibbe Bakker <sibbe.bakker@wur.nl>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
deploy = 'Rscript deploy.R'

[dependencies]
quarto = ">=1.4.550,<1.5"
r = ">=4.3,<5"
r-rsconnect = ">=1.3.1,<1.4"
r-rmarkdown = ">=2.27,<3"
