[project]
name = "1-impdh1"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sibbe Bakker <sibbe.bakker@wur.nl>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
quarto = ">=1.4.550,<1.5"
